// Header file common for C++ and HLSL code.

#define LIGHT_TYPE_DIRECTIONAL 1

#define MATERIAL_FLAG_TWOSIDED 0x1
#define MATERIAL_FLAG_ALPHA_MASK 0x2
#define MATERIAL_FLAG_HAS_MATERIAL_COLOR 0x4
#define MATERIAL_FLAG_HAS_ALBEDO_TEXTURE 0x8
#define MATERIAL_FLAG_HAS_NORMAL_TEXTURE 0x10
